### ISSUE TITLE
Make sock shop run as is should all the way

### ISSUE THREAD

**Issue by alongir** [kubeshark/sock-shop-demo#27]
We feel that Sock Shop is broken. Not every service is working, and the UI isn't functioning well. The load test isn't performing properly either. Can we go through it and ensure it works perfectly? We rely on it to check Kubeshark's functionality and performance. When Sock Shop doesn't function, we can't effectively test it.

Please install sock shop from the GH repo by default in each TF deployment. 
Also, Sock-shop has a UI, please have the link for the UI in the list of available links (e.g. grafana).

Don't try to fix the logic of sock-shop (e.g. fix the images), unless it's super easy to do.

**Comment by corest** [comment]
Done
